{"uuid": "5d91b601-8503-4b72-b187-25571eeb3784", "children": ["bd34f09e-e17c-4128-8f4f-367c30166ee3"], "befores": [{"name": "test_verifyURL", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=131.0.6778.86)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6C20D6CB5+28821]\n\t(No symbol) [0x00007FF6C2043840]\n\t(No symbol) [0x00007FF6C1EE578A]\n\t(No symbol) [0x00007FF6C1EBF4F5]\n\t(No symbol) [0x00007FF6C1F66247]\n\t(No symbol) [0x00007FF6C1F7ECE2]\n\t(No symbol) [0x00007FF6C1F5F0A3]\n\t(No symbol) [0x00007FF6C1F2A778]\n\t(No symbol) [0x00007FF6C1F2B8E1]\n\tGetHandleVerifier [0x00007FF6C240FCAD+3408013]\n\tGetHandleVerifier [0x00007FF6C242741F+3504127]\n\tGetHandleVerifier [0x00007FF6C241B5FD+3455453]\n\tGetHandleVerifier [0x00007FF6C219BDBB+835995]\n\t(No symbol) [0x00007FF6C204EB5F]\n\t(No symbol) [0x00007FF6C204A814]\n\t(No symbol) [0x00007FF6C204A9AD]\n\t(No symbol) [0x00007FF6C203A199]\n\tBaseThreadInitThunk [0x00007FFD9BD7DBE7+23]\n\tRtlUserThreadStart [0x00007FFD9D33FBEC+44]\n\n", "trace": "  File \"C:\\Users\\gakad\\PycharmProjects\\PythonProjectPractice\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\gakad\\PycharmProjects\\PythonProjectPractice\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\gakad\\PycharmProjects\\PythonProjectPractice\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\gakad\\PycharmProjects\\PythonProjectPractice\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\gakad\\PycharmProjects\\PythonProjectPractice\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\gakad\\PycharmProjects\\PythonProjectPractice\\Py Test Framework\\testuserpassword.py\", line 19, in test_verifyURL\n    driver1.maximize_window()\n    ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\gakad\\PycharmProjects\\PythonProjectPractice\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 532, in maximize_window\n    self.execute(command, None)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"C:\\Users\\gakad\\PycharmProjects\\PythonProjectPractice\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 380, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\gakad\\PycharmProjects\\PythonProjectPractice\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1732871385437, "stop": 1732871390071}], "start": 1732871385437, "stop": 1732871390119}